/**
 * Which loops have been built, as `public/ambience/<id>.m4a`.
 *
 * Generated by `node scripts/ambience.mjs`. Do not edit by hand.
 */
export const LOOP_IDS: ReadonlySet<string> = new Set([
  'rain',
  'heavy-rain',
  'thunder',
  'wind',
  'campfire',
  'firework',
  'ocean',
  'river',
  'underwater',
  'bubble',
  'whale',
  'bird',
  'morning-bird',
  'cricket',
  'frog',
  'owl',
  'chicken',
  'jungle',
  'chime',
  'clock',
  'fan',
  'book',
  'kitchen',
  'sleep',
  'city',
  'train',
  'airplane',
  'tractor',
  'restaurant',
  'countryside',
]);

/** Where one loop lives, relative to the app root. */
export function loopUrl(id: string): string {
  return `ambience/${id}.m4a`;
}
