import type { SoundId } from './audio';

/**
 * How much each sound is turned down (or up) so they all land at the same
 * loudness. Without this the set spans some 30 dB — the pig is inaudible at the
 * volume that makes the cow bearable — and a parent spends the afternoon on the
 * volume rocker. A few sounds sit deliberately off the house level: see
 * `INTENT_DB` in the script.
 *
 * Generated by `node scripts/loudness.mjs`, which renders every sound offline
 * through the real master chain and measures it. Do not edit by hand: re-run the
 * script after changing any sound, and commit what it writes.
 */
export const LOUDNESS: Readonly<Record<SoundId, number>> = {
  // interface and rewards
  'pop': 4.7171,
  'ding': 1.141,
  'boing': 6.5549,
  'chomp': 4.954,
  'tick': 3.441,
  'jingle': 0.6503,
  'puff': 1.604,
  'sample': 0.4858,
  // musical notes, per instrument
  'note:piano': 1.5359,
  'note:xylo': 1.1422,
  'note:bell': 0.7525,
  'note:guitar': 1.3687,
  'note:flute': 0.1932,
  'note:trumpet': 0.2866,
  'note:violin': 0.6304,
  'note:sax': 0.3964,
  'note:bass': 0.1921,
  // the drum kit
  'drum:kick': 0.705,
  'drum:snare': 1.0879,
  'drum:hat': 5.6803,
  'drum:tom': 0.8917,
  'drum:clap': 1.7295,
  'drum:cowbell': 2.9017,
  'drum:shaker': 3.6258,
  'drum:wood': 4.6387,
  'drum:ride': 4.1743,
  'drum:triangle': 0.9408,
  'drum:crash': 1.9508,
  // effects and animal voices
  'fx:laser': 6.1995,
  'fx:honk': 0.2865,
  'fx:siren': 0.5483,
  'fx:whistle': 0.8287,
  'fx:slide': 0.2358,
  'fx:zap': 5.002,
  'fx:sparkle': 0.5392,
  'fx:kazoo': 1.5594,
  'fx:roll': 1.4475,
  'fx:cheer': 0.7083,
  'fx:meow': 2.5084,
  'fx:bark': 3.7635,
  'fx:quack': 4.5422,
  'fx:moo': 0.3916,
  'fx:chirp': 2.1752,
  'fx:roar': 0.421,
  'fx:frog': 3.1161,
  'fx:pig': 10.3281,
  'fx:owl': 0.8459,
  'fx:elephant': 0.6826,
  'fx:sheep': 1.2941,
  'fx:cricket': 3.7829,
};
