import type { SoundId } from './audio';

/**
 * How much each sound is turned down (or up) so they all land at the same
 * loudness. Without this the set spans some 30 dB — the pig is inaudible at the
 * volume that makes the cow bearable — and a parent spends the afternoon on the
 * volume rocker. A few sounds sit deliberately off the house level: see
 * `INTENT_DB` in the script.
 *
 * Loudness here is A-weighted, so a kick and a bell that meter the same on a flat
 * meter do not get the same trim: the kick, which both an ear and a small speaker
 * hear far less of, is given the room it needs.
 *
 * Generated by `node scripts/loudness.mjs`, which renders every sound offline
 * through the real master chain and measures it. Do not edit by hand: re-run the
 * script after changing any sound, and commit what it writes.
 */
export const LOUDNESS: Readonly<Record<SoundId, number>> = {
  // interface and rewards
  pop: 3.762,
  ding: 0.8882,
  boing: 2.8727,
  chomp: 3.266,
  tick: 2.8124,
  jingle: 0.5194,
  puff: 1.1954,
  sample: 0.2885,
  // musical notes, per instrument
  'note:piano': 1.2088,
  'note:xylo': 0.9091,
  'note:bell': 0.6024,
  'note:guitar': 1.1389,
  'note:flute': 0.1605,
  'note:trumpet': 0.2385,
  'note:violin': 0.51,
  'note:sax': 0.2716,
  'note:bass': 0.1597,
  // the drum kit
  'drum:kick': 3.4233,
  'drum:snare': 0.7841,
  'drum:hat': 3.5711,
  'drum:tom': 0.6799,
  'drum:clap': 1.2645,
  'drum:cowbell': 2.0951,
  'drum:shaker': 2.1954,
  'drum:wood': 3.5359,
  'drum:ride': 2.7304,
  'drum:triangle': 0.709,
  'drum:crash': 1.4036,
  // effects and animal voices
  'fx:laser': 4.3513,
  'fx:honk': 0.15,
  'fx:siren': 0.4428,
  'fx:whistle': 0.6595,
  'fx:slide': 0.19,
  'fx:zap': 8.2192,
  'fx:sparkle': 0.4371,
  'fx:kazoo': 1.2406,
  'fx:roll': 1.024,
  'fx:cheer': 0.5654,
  'fx:meow': 1.9989,
  'fx:bark': 3.7697,
  'fx:quack': 6.755,
  'fx:moo': 0.3193,
  'fx:chirp': 1.5041,
  'fx:roar': 0.4031,
  'fx:frog': 2.8846,
  'fx:pig': 7.4578,
  'fx:owl': 0.6896,
  'fx:elephant': 0.654,
  'fx:sheep': 0.9422,
  'fx:cricket': 2.4465,
};
