import type { FxKind } from './audio';

/**
 * How many recorded takes there are of each animal, as `public/sfx/<kind>-<n>.m4a`.
 *
 * Several takes per animal so that a child pressing the same button twenty times
 * does not hear the same sample twenty times. Anything missing here keeps its
 * synthesized voice, so this file shrinking is a downgrade, never a breakage.
 *
 * Generated by `node scripts/sfx.mjs`. Do not edit by hand.
 */
export const SFX_TAKES: Readonly<Partial<Record<FxKind, number>>> = {
  bark: 2,
  chirp: 2,
  cricket: 2,
  elephant: 1,
  frog: 2,
  meow: 3,
  moo: 3,
  owl: 2,
  pig: 2,
  quack: 1,
  roar: 1,
  sheep: 3,
};

/** Where one take lives, relative to the app root. */
export function sfxUrl(kind: FxKind, take: number): string {
  return `sfx/${kind}-${take}.m4a`;
}
