import type { FxKind } from './audio';

/**
 * How many recorded takes there are of each voice, as `public/sfx/<kind>-<n>.m4a`.
 *
 * Several takes per voice so that a child pressing the same button twenty times
 * does not hear the same sample twenty times. Anything missing here keeps its
 * synthesized voice, so this file shrinking is a downgrade, never a breakage.
 *
 * Generated by `node scripts/sfx.mjs`. Do not edit by hand.
 */
export const SFX_TAKES: Readonly<Partial<Record<FxKind, number>>> = {
  bark: 3,
  chirp: 2,
  cluck: 3,
  cricket: 3,
  elephant: 3,
  frog: 3,
  goat: 3,
  growl: 3,
  horn: 3,
  horse: 3,
  meow: 3,
  monkey: 3,
  moo: 3,
  owl: 3,
  parrot: 2,
  penguin: 1,
  pig: 3,
  quack: 3,
  roar: 3,
  sheep: 3,
  siren: 3,
  squeak: 1,
  tractor: 2,
  train: 2,
};

/** Where one take lives, relative to the app root. */
export function sfxUrl(kind: FxKind, take: number): string {
  return `sfx/${kind}-${take}.m4a`;
}
